name: Capistrano

on:
    push:
        branches: [actions-cap]
jobs:
    capistrano:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1

            -   name: Setup hosts
                run: sudo echo "${{ secrets.DESTINATION_HOSTNAME }}  ${{ secrets.CAPISTRANO_HOST_ALIAS }}" | sudo tee -a /etc/hosts

            -   uses: actions/setup-ruby@v1
                with:
                    ruby-version: 2.6.x
            -   name: Run ruby bundle
                run: |
                    gem install bundler
                    bundle install

            -   name: Install Open VPN
                run: sudo apt-get install openvpn
            -   name: Connect VPN
                run: sudo openvpn --config .github/workflows/config/openvpn/openvpn.conf &
            -   name: Check Connect VPN
                run: ping -c 2 ${{ secrets.DESTINATION_HOSTNAME }}

            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.DESTINATION_HOST_PRIVATE_KEY }}
                    known_hosts: ${{ secrets.DESTINATION_HOST_KEY }}

            -   name: Run capistrano deploy for S5
                run: |
                    cd tools/cap
                    cap s5-actions deploy

            -   name: kill vpn
                if: always()
                run: sudo killall openvpn