name: Capistrano

# TODO Enable the on branches
#on:
#  push:
#    branches: [  ]
#  pull_request:
#    branches: [  ]
jobs:
    production_deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1

            -   name: Setup hosts
                run: sudo echo "${{ secrets.DESTINATION_HOSTNAME }}  ${{ secrets.CAPISTRANO_HOST_ALIAS }}" | sudo tee -a /etc/hosts

            -   uses: actions/setup-ruby@v1
                with:
                    ruby-version: 2.7
            -   name: Run ruby bundle
                run: |
                    gem install bundler
                    bundle install

            -   name: Install Open VPN
                run: sudo apt-get install openvpn
            -   name: Decode certificate
                run: |
                  echo "${{ secrets.OPENVPN_CERTIFICATE }}" > .enc_cert
                  base64 -d .enc_cert > .github/workflows/config/openvpn/openvpn.p12
            -   name: Connect VPN
                run: sudo openvpn --config .github/workflows/config/openvpn/openvpn.conf &
            -   name: Check Connect VPN
                run: ping -c 2 ${{ secrets.DESTINATION_HOSTNAME }}

            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.DESTINATION_HOST_PRIVATE_KEY }}
                    known_hosts: ${{ secrets.KNOWN_HOSTS }}

            -   name: Run capistrano deployment to UAT
                run: cap uat deploy

            -   name: kill vpn
                if: always()
                run: sudo killall openvpn
