name: PHP Static Analysis

on: pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest

    env:
      extensions: bcmath, ctype, curl, dom, gd, hash, iconv, intl, mbstring, openssl, pdo_mysql, simplexml, soap, xsl, zip, lib-libxml
      key: php-cache-v1 # can be any string, change to clear the extension cache.
      php-version: '7.4'

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache PHP extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          coverage: xdebug

      - name: Install Skywire coding standard
        run: |
          git clone https://github.com/Skywire/skywire-coding-standard.git
          cd skywire-coding-standard
          composer install
          cd ../

      - name: Run CodeSniffer with Skywire standard
        run: |
          ./skywire-coding-standard/vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
          ./skywire-coding-standard/vendor/bin/phpcs --standard=Skywire app/code/Skywire --basepath=$GITHUB_WORKSPACE app/code/[ClientNamespace] --severity=7 --report=csv --report-file=phpcs-report.csv

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: phpcs-report
          path: phpcs-report.csv